#pragma once
#ifndef __MyRenderOrder_h__
#define __MyRenderOrder_h__

#define RD_ORDER_BACKGROUND_WALL (-1000)
#define RD_ORDER_BACKGROUND_FLOOR (-999)

#define RD_TAG_FLOOR_OVERLAY_BOMBRAD (-1000)
#define RD_TAG_FLOOR_OVERLAY_POOL (-999)
#define RD_TAG_FLOOR_OVERLAY_TARGET (1000)

#define RD_ORDER_BACKGROUND_OBJ_DOOR_INSIDE (-101)
#define RD_ORDER_BACKGROUND_OBJ_DOOR_LEFT (-100)
#define RD_ORDER_BACKGROUND_OBJ_DOOR_RIGHT (-99)
#define RD_ORDER_BACKGROUND_OBJ_DOOR_FRAME (-98)

#define RD_ORDER_OBJ_BODY (1)
#define RD_ORDER_OBJ_HEAD (2)

#define RD_ORDER_FLYING_OBJ_FLY (100)

#define RD_ORDER_EFFECT_BRIMSTON_CORNER (-10000)
#define RD_ORDER_EFFECT_BRIMSTON_BEAM (10000)
#define RD_ORDER_EFFECT_BRIMSTON_HIT (15000)
#define RD_ORDER_EFFECT_UNLOCK (20000)

#define RD_ORDER_UI_SKULL (2)
#define RD_ORDER_UI_HP (1)
#define RD_ORDER_UI_BAR (0)

#endif
